### ISSUE TITLE
Install MySQL server and MySQLWorkbench on the VM

### ISSUE THREAD

**Issue by chen-regen** [wdduncan/NDPBRN#15]
Need this for one merged tooth_history table later on.

**Comment by chen-regen** [comment]
<img width="1440" alt="screen shot 2017-08-21 at 2 25 09 pm" src="https://user-images.githubusercontent.com/10854641/29533071-1eb32912-867e-11e7-9881-5a9d2258ceac.png">

**Comment by chen-regen** [comment]
<img width="1440" alt="screen shot 2017-08-21 at 2 18 32 pm" src="https://user-images.githubusercontent.com/10854641/29533077-25c15bfc-867e-11e7-9449-e8f8104d397b.png">

**Comment by chen-regen** [comment]
@wdduncan Hi Bill, I have installed MySQL server on the vm. I just attached couple of screenshots to show you the connection to MySQL with DBVisualizer and the MySQL service under Windows services utility. 
- data dir is E:\development\mysql\data (defined in :\Program Files\MySQL\MySQL Server 5.7\my.cnf)
- database "edr" was created
- DB user "edruser" was created and I can give the password to whoever will need it later on in person. I have granted all permissions on "edr" to "edruser".
- installed MySQL service as Windows service. So it should restart with the VM or manually start with Windows services utility
- MySQLWorkbench is NOT installed due to VM lack of Microsoft Visual C++ packs.

**Comment by wdduncan** [comment]
@chen-regen 
Thanks Chen! Can you please see if you can upload files using DBVis? The workbench has a nice feature that allows you to import a file into a table. This can be used to created tables or append new records. I do know not if you can do this with DBVis.

**Comment by chen-regen** [comment]
Will do Bill. I'll see if DBVis has any similar functionality. I think mysql has its own data loading util by loading csv file into a table. So probably the worst case is to use that instead.

**Comment by chen-regen** [comment]
<img width="1440" alt="screen shot 2017-08-22 at 1 11 42 pm" src="https://user-images.githubusercontent.com/10854641/29578292-c294f308-873c-11e7-8636-0d8b3e64b5f3.png">

**Comment by chen-regen** [comment]
<img width="1440" alt="screen shot 2017-08-22 at 1 13 36 pm" src="https://user-images.githubusercontent.com/10854641/29578306-d08184c2-873c-11e7-91c9-d0f681019590.png">

**Comment by chen-regen** [comment]
<img width="1440" alt="screen shot 2017-08-22 at 1 14 15 pm" src="https://user-images.githubusercontent.com/10854641/29578313-d81ad940-873c-11e7-8d91-cd5c1f26d6da.png">

**Comment by chen-regen** [comment]
<img width="1440" alt="screen shot 2017-08-22 at 1 15 00 pm" src="https://user-images.githubusercontent.com/10854641/29578328-e5827818-873c-11e7-96d2-f601010bf323.png">

**Comment by chen-regen** [comment]
<img width="1440" alt="screen shot 2017-08-22 at 1 15 52 pm" src="https://user-images.githubusercontent.com/10854641/29578335-ebd44e3a-873c-11e7-8156-fc4e88e338c6.png">

**Comment by chen-regen** [comment]
<img width="1440" alt="screen shot 2017-08-22 at 1 17 06 pm" src="https://user-images.githubusercontent.com/10854641/29578349-f646e300-873c-11e7-8bf4-bfe52efff370.png">

**Comment by chen-regen** [comment]
<img width="1440" alt="screen shot 2017-08-22 at 1 17 26 pm" src="https://user-images.githubusercontent.com/10854641/29578353-fbf5cc44-873c-11e7-9e74-7df1b7656db8.png">
