### ISSUE TITLE
Discuss re-running patient queries

### ISSUE THREAD

**Issue by wdduncan** [wdduncan/NDPBRN#17]
The new databases from ES contain few patients in the patient table than the previous versions. 

Here are the numbers:

Practice 1: 1028 patients from the new database file vs. 1236 patients from the previous file;
 
Practice 10: 2088 patients from the new database file vs. 2723 patients from the previous file;
 
Practice 25: 1137 patients from the new database file vs. 2144 patients from the previous file.

We need to decide if we are going to re-run the queries to recreate the tab delimited patient files.

**Comment by jimjzheng** [comment]
Look like the patient number counts from the new database files were significantly lower than the patient number counts from the previous database files.

**Comment by Jaymedam** [comment]
I feel these are the right patient counts as the date criteria if fixed for the new data bases!

**Comment by knappkl** [comment]
Bill will provide Ted with the query to run on the databases to produce new Patient tables. New Provider tables are not necessary.
