### ISSUE TITLE
Verify ES databases

### ISSUE THREAD

**Issue by wdduncan** [wdduncan/NDPBRN#18]
The most recent bolus of ES databases were filtered for patients that: 

1. RCT/PCR between 2000 and 2015. 
2. Patients that have two years of followup data

We need to verify that this is case.

Question: By two years of followup, do we mean two years of data after the PCR/RCT or just two years of visit data?

**Comment by jimjzheng** [comment]
Hi Bill,

Just wanted to make sure I understand your question correctly:

Question: By two years of followup, do we mean two years of (PCR/RCT) data after the PCR/RCT or just two years of (any dental) visit data?

Am I rephrasing your question right?

Thanks,
Jim

**Comment by wdduncan** [comment]
I sent a clarification email about this.

**Comment by jimjzheng** [comment]
Thanks, Bill!

Jim

**Comment by wdduncan** [comment]
According to email it should be two years after first PCR/RCT.
