### ISSUE TITLE
Loading practice information to graphs

### ISSUE THREAD

**Issue by knappkl** [wdduncan/NDPBRN#20]

**Comment by chen-regen** [comment]
Hi @wdduncan  I have tried the TriG syntax and experimented with prac_1 and prac_2 providers. Below are sample output.

Add ":" prefix before the beginning of the ttl:
@prefix : <http://purl.regenstrief.org/NDPBRN/dental-practice#> .
:G_A_1 {
practice:A_1 rdf:type <http://purl.obolibrary.org/obo/OHD_0000013> .
practice:A_1 rdfs:label "practice_A_1"^^xsd:string .
practice:A_1 <http://purl.obolibrary.org/obo/OHD_0000273> "NDPBRN practice A_1" .

provider:A_1_1_1 rdf:type <http://purl.obolibrary.org/obo/OHD_0000051> .
provider:A_1_1_1 rdf:type owl:NamedIndividual .
provider:A_1_1_1 rdfs:label "provider A_1_1_1"^^xsd:string .
provider:A_1_1_1 <http://purl.obolibrary.org/obo/OHD_0000273> "NDPBRN practice A_1" .

Add "}" end of the file:
provider:A_1_1_15 obo:FMA_85868 practice:A_1 . }

So I did following Sparql:
select (count(distinct ?p_i) as ?cnt) where { 
    ?p_i rdf:type obo:OHD_0000051 . 
    graph :G_A_2
    {?p_i a ?p_t .}
}

It returns me practice 2 count . If i use ":G_A_1", it returns me practice 1 count. If I comment out "graph :G_A_2", it returns me the total from both.
