### ISSUE TITLE
Compare Aparna's Dentrix tooth history files with Ted's new files to see if they're compatible

### ISSUE THREAD

**Issue by knappkl** [wdduncan/NDPBRN#26]

**Comment by chen-regen** [comment]
Reviewed Aparna's dentrix PRAC_1 tooth history file E:\SQL queries\Dentrix queries\Dentrix Results - Practices\RESULTS\TABLES\Final Tables\practices\PRAC1\Dentrix_Pract1_Tooth_History.txt. It looks fine. The headers are (for documenting purpose): 
NDPBRN_ID    PATIENT_ID    BIRTH_DATE    SEX    TABLE_NAME    DATE_COMPLETED    DATE_ENTERED    TRAN_DATE    DESCRIPTION    TOOTH   SURFACE     ACTION_CODE    ACTION_CODE_DESCRIPTION   SERVICE_CODE    ADA_CODE    ADA_CODE_DESCRIPTION    TOOTH_DATA    SURFACE_DETAIL    PROVIDER_ID    DB_PRACTICE_ID.
I ran her file with procedure 1 and translation: filling and endodontic. It works fine.

Ted's PRAC_1 tooth history file headers are: 
practice_id     patient_id      birth_date      sex     table_name      date_completed  date_entered    tran_date       description     tooth   surface action_code     action_code_description service_code    ada_code        ada_code_description    tooth_data      surface_detail  provider_id     db_practice_id

So they are equivalent at this point.

**Comment by chen-regen** [comment]
One thing I need bring to Bill's attention. @wdduncan Bill, can you confirm if they are going to use the extracted tooth history files to merge and load those into one big table? I am not sure if there's anything else you want to use besides tooth history.

**Comment by wdduncan** [comment]
Right now we are focused on tooth history. It will useful in the future to
pull in the patient and provider information.

The structure should be as follows:

One table with all ES tooth history records.
One table with all Dentrix tooth history recrods.

One view that combines the overlapping portions of the above two tables.

Make sense?

Bill

**Comment by chen-regen** [comment]
Thank you Bill. Okay, I think this issue can be marked as done too.
