### ISSUE TITLE
Combine EagleSoft Tooth History Tables

### ISSUE THREAD

**Issue by knappkl** [wdduncan/NDPBRN#5]

**Comment by knappkl** [comment]
completed by Ted; in Box Health folder; @jimjzheng  will move to VM

**Comment by knappkl** [comment]
@chen-regen  needs to review before calling this complete

**Comment by chen-regen** [comment]
Can somebody tell me where Ted's combined tooth history file is?

**Comment by jimjzheng** [comment]
Hi Chen,

I have moved that big file from the Box to the VM E drive under the folder “Data”, in which we have kept all tooth history files and the provider and the patient files together.

Thanks!

Jim

**Comment by chen-regen** [comment]
Thank you Jim. Is this one combined: E:\data\All_tooth_history\All_tooth_history_from_data.txt ?

**Comment by jimjzheng** [comment]
Yes, this is it. Thanks, Chen!

Jim

**Comment by chen-regen** [comment]
Thanks Jim.
I reviewed that big file by looking at some beginning lines and bottom lines. It's 1.2G in size. One cannot even open it with textpad. The headers are consistent as:
practice_id     patient_id      birth_date      sex     table_name      date_completed  date_entered    tran_date       description     tooth   surface action_code     action_code_description service_code    ada_code        ada_code_description    tooth_data      surface_detail  provider_id     db_practice_id

Format looks good too.
The only thing is: some of the rows missing "db_practice_id". They are not "transactions" rows, so it doesn't affect translation. They are something like "existing_services". Need @wdduncan Bill's OK on this.

**Comment by jimjzheng** [comment]
Sounds good, thanks Chen!

Jim

**Comment by wdduncan** [comment]
Hi Jim & Chen,

Yes, records pulled from the existing_services and patient_conditions
tables will not have a db_practice_id associated with them, only patient
and provider ids.

For large files, I view them on my iMac using vi. Emacs might work too. I'm
not not sure what you can you use on a Windows machine. Perhaps edit?

To validate the files we can spot check the number of records imported from
a practice against the number of lines in a practice's tooth history file.
They only differ by 1.

Please go ahead and try to load.

Thanks,
Bill

**Comment by chen-regen** [comment]
Thanks Bill. I was cautious about the missing db_practice_id. If you think it's ok, we are good with this task. I am going to mark this issue as "done". The other issue "# 19" is about loading the data into MySQL.

**Comment by wdduncan** [comment]
Yes. I think we are good on this issue ;)
